name: Deploy Web App

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    permissions:
      id-token: write
      contents: read
    environment: "production"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload assets
        run: |
          aws s3 cp ./index.html s3://${{ secrets.S3_BUCKET_NAME }}/index.html
          aws s3 cp --recursive ./static s3://${{ secrets.S3_BUCKET_NAME }}/static/

      - name: Invalidate cdn
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_ORIGIN_ID }} --paths "/*" "/**/*"
