name: Deploy Web App

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    environment: "production"
    steps:
      - uses: AutoModality/action-clean@v1

      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Upload assets
        run: |
          aws s3 cp ./index.html s3://${{ secrets.S3_BUCKET_NAME }}/index.html
          aws s3 cp --recursive ./static s3://${{ inputs.assets_bucket }}/static/

      - name: Invalidate cdn
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_ORIGIN_ID }} --paths "/*" "/**/*"
